# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Faghelgapp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Faghelgapp
  pod 'NibDesignable'
  pod 'RealmSwift'
  pod 'Kingfisher', '~> 3.0'
  pod 'ADALiOS'
  pod 'Fabric'
  pod 'Crashlytics'

  target 'FaghelgappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'Faghelgapp'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
    end
end
