# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
inhibit_all_warnings!
target 'Faghelgapp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Faghelgapp
  pod 'NibDesignable'
  pod 'RealmSwift'
  pod 'Kingfisher', '~> 3.0'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'SwiftLint'

  target 'FaghelgappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
